show-codecov-path

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -33,28 +33,28 @@
 
      - name: Swift Test
        run: |
-          mkdir -p .build/debug
-          export LLVM_PROFILE_FILE="$(pwd)/.build/debug/code-%p.profraw"
-          swift test --enable-code-coverage --verbose
+          swift test \
+          --enable-code-coverage \
+          --show-codecov-path
 
-     - name: Merge Coverage Data
-       run: |
-         xcrun llvm-profdata merge -sparse .build/debug/code-*.profraw -o .build/debug/default.profdata
-
-     - name: Extract Code Coverage
-       run: |
-         TARGET_EXECUTABLE=$(find .build/debug -type f -perm +111 | grep -E     "(Tests|xctest|test)" || true)
-
-         if [ -z "$TARGET_EXECUTABLE" ]; then
-           echo "⚠️ Error: Test executable not found!"
-           exit 1
-         fi
-
-         xcrun llvm-cov report "$TARGET_EXECUTABLE" \
-           -instr-profile .build/debug/default.profdata \
-           > coverage-report.txt
-
-         tail -n 5 coverage-report.txt > pr_coverage_summary.txt
+#     - name: Merge Coverage Data
+#       run: |
+#         xcrun llvm-profdata merge -sparse .build/debug/code-*.profraw -o .build/debug/default.profdata
+#
+#     - name: Extract Code Coverage
+#       run: |
+#         TARGET_EXECUTABLE=$(find .build/debug -type f -perm +111 | grep -E     "(Tests|xctest|test)" || true)
+#
+#         if [ -z "$TARGET_EXECUTABLE" ]; then
+#           echo "⚠️ Error: Test executable not found!"
+#           exit 1
+#         fi
+#
+#         xcrun llvm-cov report "$TARGET_EXECUTABLE" \
+#           -instr-profile .build/debug/default.profdata \
+#           > coverage-report.txt
+#
+#         tail -n 5 coverage-report.txt > pr_coverage_summary.txt
 
 #     - name: Test
 #       run: |
@@ -67,48 +67,48 @@
 #            -skipMacroValidation \
 #            -quiet
 
-     - name: Comment on Pull Request
-       if: github.event_name == 'pull_request'
-       uses: actions/github-script@v6
-       with:
-         script: |
-            const fs = require('fs');
-            const coverageOutput = fs.readFileSync('pr_coverage_summary.txt', 'utf8');
-
-            const newComment = `
-            ### 🛡️ Code Coverage Report
-            
-            \`\`\`
-            ${coverageOutput}
-            \`\`\`
-
-            _Generated by GitHub Actions._
-            `;
-
-            // Fetch existing comments
-            const comments = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.payload.pull_request.number,
-            });
-
-            // Identify and delete previous bot comments
-            const botComments = comments.data.filter(comment =>
-              comment.body.includes("### 🛡️ Code Coverage Report")
-            );
-
-            for (const botComment of botComments) {
-              await github.rest.issues.deleteComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                comment_id: botComment.id,
-              });
-            }
-
-            // Create a comment on the pull request
-            await github.rest.issues.createComment({
-              issue_number: context.payload.pull_request.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: newComment,
-            });
+#     - name: Comment on Pull Request
+#       if: github.event_name == 'pull_request'
+#       uses: actions/github-script@v6
+#       with:
+#         script: |
+#            const fs = require('fs');
+#            const coverageOutput = fs.readFileSync('pr_coverage_summary.txt', 'utf8');
+#
+#            const newComment = `
+#            ### 🛡️ Code Coverage Report
+#            
+#            \`\`\`
+#            ${coverageOutput}
+#            \`\`\`
+#
+#            _Generated by GitHub Actions._
+#            `;
+#
+#            // Fetch existing comments
+#            const comments = await github.rest.issues.listComments({
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              issue_number: context.payload.pull_request.number,
+#            });
+#
+#            // Identify and delete previous bot comments
+#            const botComments = comments.data.filter(comment =>
+#              comment.body.includes("### 🛡️ Code Coverage Report")
+#            );
+#
+#            for (const botComment of botComments) {
+#              await github.rest.issues.deleteComment({
+#                owner: context.repo.owner,
+#                repo: context.repo.repo,
+#                comment_id: botComment.id,
+#              });
+#            }
+#
+#            // Create a comment on the pull request
+#            await github.rest.issues.createComment({
+#              issue_number: context.payload.pull_request.number,
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#              body: newComment,
+#            });
